# https://hub.docker.com/r/linuxserver/duplicati
version: "3.9"
services:
  duplicati:
    deploy:
        resources:
            limits:
              cpus: "0.50"
              memory: 512M
            reservations:
              cpus: "0.25"
              memory: 128M
    image: linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=1000
      - TZ=America/Sao_Paulo
      - CLI_ARGS= #optional
    volumes:
      - /docker/data/duplicati/config:/config
      - /:/source
    ports:
      - 8200:8200
    restart: unless-stopped
    privileged: true