version: '3.5'
services:
    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        user: ${PUID}:${PGID}
        volumes:
            - jellyfin-config:/config
            - ${dockerData}/jellyfin/Movies:/media/movies
            - ${dockerData}/jellyfin/Shows:/media/tvshows
            - ${dockerData}/jellyfin/cache:/cache
        ports:
            - 8096:8096
            - 8920:8920 #optional
            - 7359:7359/udp #optional
            - 1900:1900/udp #optional
        restart: unless-stopped
        environment:
            - TZ=${TIMEZONE}
            - VERSION=docker
    
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        environment:
                - TZ=${TIMEZONE}
        ports:
                - 5055:5055
        volumes:
                - jellyseerr-config:/app/config
        restart: unless-stopped
    
    bazarr:
        image: ghcr.io/linuxserver/bazarr
        container_name: bazarr
        environment:
            - TZ=${TIMEZONE}
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - bazarr-config:/config
            - ${dockerData}/jellyfin/Movies:/movies
            - ${dockerData}/jellyfin/Shows:/tv
        ports:
            - 6767:6767
        restart: unless-stopped    

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        privileged: true
        depends_on:
            - prowlarr
        volumes:
            - sonarr-config:/config
            - ${dockerData}/video/downloads/tv-sonarr:/downloads/tv-sonarr
            - ${dockerData}/jellyfin/Shows:/tv
        environment:
            - TZ=${TIMEZONE}
            - PUID=${PUID}
            - PGID=${PGID}
        ports:
            - 8989:8989

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        privileged: true
        depends_on:
            - prowlarr
        volumes:
            - radarr-config:/config
            - ${dockerData}/video/downloads/radarr:/downloads/radarr
            - ${dockerData}/jellyfin/Movies:/movies
        environment:
            - TZ=${TIMEZONE}
            - PUID=${PUID}
            - PGID=${PGID}
        ports:
            - 7878:7878
    
    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TIMEZONE}
            - UMASK_SET=022
            - WEBUI_PORT=8090
        ports:
            - 8090:8090
        volumes:
            - qbittorrent-config:/config
            - ${dockerData}/video/downloads:/downloads 
        restart: unless-stopped

    prowlarr:
        image: linuxserver/prowlarr
        container_name: prowlarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TIMEZONE}
        ports:
            - 9696:9696
        volumes:
            - prowlarr-config:/config
        restart: unless-stopped
        depends_on:
            - qbittorrent

volumes:
    jellyfin-config:
        driver: local
    jellyseerr-config:
        driver: local
    bazarr-config:
        driver: local
    sonarr-config:
        driver: local
    radarr-config:
        driver: local
    overseerr-config:
        driver: local
    prowlarr-config:
        driver: local
    qbittorrent-config:
        driver: local