global:
  scrape_interval: 15s #Scrape interval to every 15 seconds.
  evaluation_interval: 15s #Evaluate rules every 15 seconds.

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

scrape_configs:
 - job_name: “prometheus”
   scrape_interval: 5s
   metrics_path: /metrics
   static_configs:
    - targets: 
      - localhost:9090
 - job_name: cadvisor
   scrape_interval: 5s
   static_configs:
    - targets: 
      - prometheus0001:8080
      - prometheus0002:8080
      - prometheus0003:8080
      - prometheus0004:8080
      - prometheus0005:8080
      - prometheus0006:8080
 - job_name: “node”
   static_configs:
    - targets: 
      - prometheus0001:8100
      - prometheus0002:8100
      - prometheus0003:8100
      - prometheus0004:8100
      - prometheus0005:8100
      - prometheus0006:8100