version: '3'

services:
  whatsupdocker:
    #https://fmartinou.github.io/whats-up-docker/#/
    image: fmartinou/whats-up-docker
    container_name: wud
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_CERTS}:${DOCKER_CERTS}:ro
      - ${DOCKER_APPS}:${DOCKER_APPS}
    ports:
      - 3030:3000
    healthcheck:
      test: wget --no-verbose --tries=1 --no-check-certificate --spider http://localhost:3000
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s       
    restart: unless-stopped
    environment:
      WUD_WATCHER_LOCAL_SOCKET: /var/run/docker.sock
      WUD_LOG_FORMAT: json
      TZ: ${TIMEZONE}
      WUD_REGISTRY_HUB_LOGIN: ${WUD_REGISTRY_HUB_LOGIN}
      WUD_REGISTRY_HUB_PASSWORD: ${WUD_REGISTRY_HUB_PASSWORD}
      WUD_REGISTRY_GHCR_TOKEN: ${WUD_REGISTRY_GHCR_TOKEN}

      WUD_TRIGGER_DOCKER_OLD_IMAGE_PRUNE: "true"
      WUD_TRIGGER_DOCKERCOMPOSE_GRAFANA_FILE: ${DOCKER_APPS}/grafana/docker-compose.yaml
      WUD_TRIGGER_DOCKERCOMPOSE_GRAFANA_PRUNE: "true"
      WUD_TRIGGER_DOCKERCOMPOSE_HASSISTANT_FILE: ${DOCKER_APPS}/hassistant/docker-compose.yaml
      WUD_TRIGGER_DOCKERCOMPOSE_HASSISTANT_PRUNE: "true"
      WUD_TRIGGER_DOCKERCOMPOSE_JELLYFIN_FILE: ${DOCKER_APPS}/jellyfin/docker-compose.yaml
      WUD_TRIGGER_DOCKERCOMPOSE_JELLYFIN_PRUNE: "true"
      WUD_TRIGGER_DOCKERCOMPOSE_MONITOR_FILE: ${DOCKER_APPS}/monitor/docker-compose.yaml
      WUD_TRIGGER_DOCKERCOMPOSE_MONITOR_PRUNE: "true"
      WUD_TRIGGER_DOCKERCOMPOSE_PORTAINER_AGENT_FILE: ${DOCKER_APPS}/portainer-agent/docker-compose.yaml
      WUD_TRIGGER_DOCKERCOMPOSE_PORTAINER_AGENT_PRUNE: "true"
      WUD_TRIGGER_DOCKERCOMPOSE_RECOGNITION_FILE: ${DOCKER_APPS}/recognition/docker-compose.yaml
      WUD_TRIGGER_DOCKERCOMPOSE_RECOGNITION_PRUNE: "true"

      WUD_WATCHER_SERVER00001_HOST: ${WUD_WATCHER_SERVER00001_HOST}
      WUD_WATCHER_SERVER00001_PORT: ${WUD_WATCHER_SERVER00001_PORT}
      WUD_WATCHER_SERVER00001_CAFILE: ${WUD_WATCHER_SERVER00001_CAFILE}
      WUD_WATCHER_SERVER00001_CERTFILE: ${WUD_WATCHER_SERVER00001_CERTFILE}
      WUD_WATCHER_SERVER00001_KEYFILE: ${WUD_WATCHER_SERVER00001_KEYFILE}
      WUD_WATCHER_SERVER00001_WATCHALL: ${WUD_WATCHER_SERVER00001_WATCHALL}

      WUD_WATCHER_SERVER00002_HOST: ${WUD_WATCHER_SERVER00002_HOST}
      WUD_WATCHER_SERVER00002_PORT: ${WUD_WATCHER_SERVER00002_PORT}
      WUD_WATCHER_SERVER00002_CAFILE: ${WUD_WATCHER_SERVER00002_CAFILE}
      WUD_WATCHER_SERVER00002_CERTFILE: ${WUD_WATCHER_SERVER00002_CERTFILE}
      WUD_WATCHER_SERVER00002_KEYFILE: ${WUD_WATCHER_SERVER00002_KEYFILE}
      WUD_WATCHER_SERVER00002_WATCHALL: ${WUD_WATCHER_SERVER00002_WATCHALL}

      WUD_WATCHER_SERVER00003_HOST: ${WUD_WATCHER_SERVER00003_HOST}
      WUD_WATCHER_SERVER00003_PORT: ${WUD_WATCHER_SERVER00003_PORT}
      WUD_WATCHER_SERVER00003_CAFILE: ${WUD_WATCHER_SERVER00003_CAFILE}
      WUD_WATCHER_SERVER00003_CERTFILE: ${WUD_WATCHER_SERVER00003_CERTFILE}
      WUD_WATCHER_SERVER00003_KEYFILE: ${WUD_WATCHER_SERVER00003_KEYFILE}
      WUD_WATCHER_SERVER00003_WATCHALL: ${WUD_WATCHER_SERVER00003_WATCHALL}

      WUD_WATCHER_SERVER00004_HOST: ${WUD_WATCHER_SERVER00004_HOST}
      WUD_WATCHER_SERVER00004_PORT: ${WUD_WATCHER_SERVER00004_PORT}
      WUD_WATCHER_SERVER00004_CAFILE: ${WUD_WATCHER_SERVER00004_CAFILE}
      WUD_WATCHER_SERVER00004_CERTFILE: ${WUD_WATCHER_SERVER00004_CERTFILE}
      WUD_WATCHER_SERVER00004_KEYFILE: ${WUD_WATCHER_SERVER00004_KEYFILE}
      WUD_WATCHER_SERVER00004_WATCHALL: ${WUD_WATCHER_SERVER00004_WATCHALL}

      WUD_WATCHER_SERVER00005_HOST: ${WUD_WATCHER_SERVER00005_HOST}
      WUD_WATCHER_SERVER00005_PORT: ${WUD_WATCHER_SERVER00005_PORT}
      WUD_WATCHER_SERVER00005_CAFILE: ${WUD_WATCHER_SERVER00005_CAFILE}
      WUD_WATCHER_SERVER00005_CERTFILE: ${WUD_WATCHER_SERVER00005_CERTFILE}
      WUD_WATCHER_SERVER00005_KEYFILE: ${WUD_WATCHER_SERVER00005_KEYFILE}
      WUD_WATCHER_SERVER00005_WATCHALL: ${WUD_WATCHER_SERVER00005_WATCHALL}

