default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.15.0/24 # Add the IP address of the proxy server or ip of the host where the docker engine is installled
    - 192.168.15.65
    - 10.10.80.0/24
    - 127.0.0.1
    - ::1
  ip_ban_enabled: true
  login_attempts_threshold: 5

api:

homeassistant:
  packages: !include_dir_named packages

panel_iframe:
  vscode:
    title: Visual Studio Code
    icon: mdi:microsoft-visual-studio-code
    url: https://vscode.karva.work/
    require_admin: true
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: https://nodered.karva.work/
    require_admin: true
  mqtt:
    title: EMQX
    icon: mdi:queue-first-in-last-out
    url: https://emqx.karva.work/
    require_admin: true
  esphome:
    title: ESP Home
    icon: mdi:chip
    url: https://esphome.karva.work/
    require_admin: true
  
recorder:
  db_url: !secret mysql_url
  purge_keep_days: 30

frontend:
  themes: !include_dir_merge_named themes

#sensor: !include_dir_merge_list sensors
#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

# Text to speech
tts:
  - platform: google_translate